#!/bin/bash

if [[ ! -n "$DISABLE_WAYLAND" && -n "$WAYLAND_DISPLAY" ]]; then
  WAYLAND_OPTS="--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland"
fi

exec "$SNAP/usr/share/discord/Discord" --use-tray-icon --no-sandbox --disable-seccomp-filter-sandbox $WAYLAND_OPTS "$@"
