name: discord
base: core18
adopt-info: discord
summary: Chat for Communities and Friends
description: |
 Discord is the easiest way to communicate over voice, video and text.
 Chat, hang out, and stay close with your friends and communities.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
compression: lzo

parts:
  disable-updater:
    plugin: nil
    override-pull: |
      cat <<'EOF' > disable-updater.sh
      #!/bin/bash
      CONFIG_FILE="$SNAP_USER_DATA"/.config/discord/settings.json
      if ! [ -f "$CONFIG_FILE" ]; then
        echo '{}' > "$CONFIG_FILE"
      fi
      ORIG_JSON=$(cat "$CONFIG_FILE")
      NEW_JSON=$(jq '.SKIP_HOST_UPDATE = true' < "$CONFIG_FILE")
      if [ "$ORIG_JSON" != "$NEW_JSON" ]; then
        echo "$NEW_JSON" > "$CONFIG_FILE"
      fi
      exec "$@"
      EOF
    override-build: |
      install -m755 -D -t $SNAPCRAFT_PART_INSTALL/bin disable-updater.sh
    stage-packages:
      - jq

  libappindicator:
    plugin: nil
    stage-packages:
      - libappindicator3-1
    prime:
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdbusmenu*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libappindicator*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libindicator*.so*

  discord:
    after: [libappindicator]
    plugin: dump
    source: "https://discord.com/api/download?platform=linux&format=deb"
    source-type: deb
    override-build: |
      snapcraftctl build
      DEB_API="https://discord.com/api/download?platform=linux&format=deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f6)
      snapcraftctl set-version $(echo $VERSION)
      rm $SNAPCRAFT_PART_INSTALL/usr/share/discord/chrome-sandbox
      # Correct path to icon.
      sed -i 's|Icon=discord|Icon=/usr/share/discord/discord\.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/discord/discord.desktop
    build-packages:
      - curl
      - sed
    stage-packages:
      - libatomic1
      - libc++1
      - libnspr4
      - libnss3
      - libxss1
      - xdg-utils
    prime:
      - -usr/bin/xdg-open

  cleanup:
    after: [discord]
    plugin: nil
    build-snaps: [gnome-3-28-1804]
    override-prime: |
        set -eux
        cd /snap/gnome-3-28-1804/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  discord:
    extensions: [gnome-3-28]
    command: usr/share/discord/Discord --no-sandbox
    command-chain: [bin/disable-updater.sh]
    autostart: discord.desktop
    desktop: usr/share/applications/discord.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
      # are used and do not fall back to Notification Area applets
      # or disappear completely.
      XDG_CURRENT_DESKTOP: Unity
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - audio-playback
      - audio-record
      - browser-support
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - system-observe
      - unity7
